repository: liu115/liu115.github.io
title: Yueh-Cheng Liu
email: ycliu [at] gmail.com
keywords: yueh-cheng liu, ycliu
description: Yueh-Cheng Liu is a research assistant at National Tsing Hua University. His research interests include computer vision, robot learning, and 3D scene understanding 
domain: liu115.github.io
url: https://liu115.github.io
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: G-LQ2XSTYRW9
teaser: /assets/images/avatar.jpg

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
    - jekyll-include-cache

masthead_title: "Home"

author:
  name: Yueh-Cheng Liu
  avatar: "/assets/images/avatar.jpg"
  bio: "PhD student at TUM"
  location: "Munich, Germany"
  links:
    - label: "CV"
      icon: "far fa-fw fa-file-pdf"
      url: "/assets/pdf/cv.pdf"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/yueh-cheng-liu-66a42912b/"
    - label: "Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com.tw/citations?user=qCecu60AAAAJ"

atom_feed:
  hide: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-LQ2XSTYRW9"
    anonymize_ip: false # default
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
